# azure-sdk-for-go 和 azure-rest-api-specs 的本地路径
SdkPath: d:/azure-sdk-for-go
SpecPath: d:/azure-rest-api-specs

# 指定 autorest.go 和 autorest.gotest 版本, 也可使用 `本地包路径` 或 `压缩包`
CodeGenVersion: # https://github.com/Azure/autorest.go
  go: "@autorest/go@4.0.0-preview.60"
  gotest: "@autorest/go@4.7.0"

# 需要release的 arm service(mgmt)
ArmServices:
  redis:
  cdn: asdfasfd
  mysql:
    armmysql: asdfsdaf
    armmysqlx:  sdfa
    armmongo:

# config autorest.md
AutorestMDConfig: |
  

# config `generator release-v2` cmd flags
ReleaseV2Flags:
  # string
  forceStableVersion: # 用不到，可以用 --version-number 替代
  goVersion: 
  packageConfig:
  packageTitle:
  releaseDate: "2023-11-10"
  specRepo:
  # 主要用于specs名字与arm名字不一样
  specRPName: 
  # 用于auto create release pr
  token: $env:GITHUB_TOKEN_JH
  versionNumber: 
  # bool
  skipCreateBranch: false
  skipGenerateExample: false
  updateSpecVersion: true
